#!/bin/bash

echo "Content-Type: image/jpeg"
echo "Cache-Control: no-cache"
echo ""
ffmpeg -rtsp_transport tcp -i "rtsp://admin:PASSWORD@10.10.10.171:554/Streaming/Channels/102" -vframes 1 -f image2pipe -an -
